spring:
  application:
    name: vueag
#  datasource:
#    url: r2dbc:sqlserver://;serverName=localhost;databaseName=students;encrypt=true;trustServerCertificate=true;
#    username: sa
#    password: kolob_OK1
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  r2dbc:
#    url: r2dbc:sqlserver://;serverName=localhost;databaseName=students;encrypt=true;trustServerCertificate=true;
#    url: r2dbc:mssql:/localhost/students
#    username: sa
#    password: kolob_OK1
#    initialization-mode: always
  r2dbc:
    url: r2dbc:sqlserver://localhost:1433
    username: sa
    password: kolob_OK1
    name: students
# server:
#  port: 1433
#  server.port=
#  spring.r2dbc.url=r2dbc:mssql:/<host>/<db-name>
#  spring.r2dbc.username=
#  spring.r2dbc.password=
#  spring.r2dbc.initialization-mode=always
#  spring.main.web-application-type=reactive
